### ISSUE TITLE
Feature Request - Add Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by Felipefpl** [InfinityTools/WeiduInstallTool#3]
I made a brazilian portuguese translation for the tool. I noticed in the language file there is an entry for portuguese but not brazilian portuguese. Could you please add an entry for it to translate it in the future?
[wit.pt_br.properties.zip](https://github.com/InfinityTools/WeiduInstallTool/files/13058843/wit.pt_br.properties.zip)

**Comment by Argent77** [comment]
Thank you. At a quick glance I can see lots of symbolic definitions of unicode characters. The `.properties` file does support UTF-8 characters directly. It would make updating the file easier if they are replaced by utf-8 characters directly.

> I noticed in the language file there is an entry for portuguese but not brazilian portuguese. Could you please add an entry for it to translate it in the future?

Do you mean this line: `ui.charsets.portuguese`? That line is just used as a general hint for a specific code page that can be selected in the character encoding menu. Adding more example languages or longer language names would make the menu entry too bulky.

**Comment by Felipefpl** [comment]
> Thank you. At a quick glance I can see lots of symbolic definitions of unicode characters. The `.properties` file does support UTF-8 characters directly. It would make updating the file easier if they are replaced by utf-8 characters directly.

What do you mean replaced by utf-8 characters? I didnt insert any symbols in the file, i just translated it.

> Do you mean this line: `ui.charsets.portuguese`? That line is just used as a general hint for a specific code page that can be selected in the character encoding menu. Adding more example languages or longer language names would make the menu entry too bulky.

I see, i just hope this dont create any problems in the future since the encoding for portuguese from Portugal and brazilian portuguese arent the same.

**Comment by Argent77** [comment]
> What do you mean replaced by utf-8 characters? I didnt insert any symbols in the file, i just translated it.

I mean lines line like this:
```properties
ui.main.windowTitle.state.running = em execu\u00e7\u00e3o
```
The unicode symbols (`\u00e7` and `\u00e3`) can be written as literal characters (`ç` and `ã`).

It could be that your editor added these symbols automatically. There might be an option turn this auto-conversion off, or maybe switching to UTF-8 encoding turns it off automatically.

> I see, i just hope this dont create any problems in the future since the encoding for portuguese from Portugal and brazilian portuguese arent the same.

I've been using the charset hint `Portuguese` for the the code page "CP860" which, according to [Wikipedia](https://en.wikipedia.org/wiki/Code_page_860) was primarily used for Portuguese text on DOS. The wiki article also mentions that Brazilian Portuguese text was mostly encoded by CP850. In that case the current description hints are correct and no further change is needed.

**Comment by Felipefpl** [comment]
> I mean lines like this:
> 
> ```ini
> ui.main.windowTitle.state.running = em execu\u00e7\u00e3o
> ```
> 
> The unicode symbols (`\u00e7` and `\u00e3`) can be written as literal characters (`ç` and `ã`):
> 
> ```ini
> ui.main.windowTitle.state.running = em execução
> ```
> 
> It could be that your editor added these symbols automatically. There might be an option turn this auto-conversion off, or maybe switching to UTF-8 encoding turns it off automatically.

I see, this didnt happen before, the software i used to translate NEVER added those symbols in the translations i made for your mods and i didnt make any changes to the editor, i only changed the file name adding pt_br to its name. Could it be a file's problem or something?

> I've been using the charset hint `Portuguese` for the the code page "CP860" which, according to [Wikipedia](https://en.wikipedia.org/wiki/Code_page_860) was primarily used for Portuguese text on DOS. The wiki article also mentions that Brazilian Portuguese text was mostly encoded by CP850. In that case the current description hints are correct and no further change is needed.

I understand, good to know. :)

**Comment by Argent77** [comment]
> I see, this didnt happen before, the software i used to translate NEVER added those symbols in the translations i made for your mods and i didnt make any changes to the editor, i only changed the file name adding pt_br to its name. Could it be a file's problem or something?

My guess is that your software edited the file in ANSI encoding and tried to be "smart" by adding these symbols to represent unicode characters. It could be that your software automatically resolves these issues if you switch to UTF-8 encoding.

Btw, I have added a few more lines to the app. Could you translate them as well?
```
ui.main.modLocation.message.title = Mod folder outside of game directory
ui.main.modLocation.message.header = The mod folder location may cause text\ndisplay issues during the installation process.
ui.main.modLocation.message.content = Continue anyway?
```

**Comment by Felipefpl** [comment]
> My guess is that your software edited the file in ANSI encoding and tried to be "smart" by adding these symbols to represent unicode characters. It could be that your software automatically resolves these issues if you switch to UTF-8 encoding.

I see, i should have changed the file to utf-8 to prevent this.
 
> Btw, I have added a few more lines to the app. Could you translate them as well?
> 
> ```
> ui.main.modLocation.message.title = Mod folder outside of game directory
> ui.main.modLocation.message.header = The mod folder location may cause text\ndisplay issues during the installation process.
> ui.main.modLocation.message.content = Continue anyway?

I prefer to wait some time if you dont mind. After all, the project is at the beginning and i believe more strings will come, right? ;)

**Comment by Argent77** [comment]
> I prefer to wait some time if you dont mind. After all, the project is at the beginning and i believe more strings will come, right? ;)

That's true.

In any case, translation file from your first comment has been [included](https://github.com/InfinityTools/WeiduInstallTool/blob/devel/src/main/resources/l10n/wit_pt_BR.properties) and will be available with the next release candidate.
